// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
	export interface GlobalComponents {
		AAvatar: typeof import('ant-design-vue/es')['Avatar'];
		ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb'];
		ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem'];
		AButton: typeof import('ant-design-vue/es')['Button'];
		ACard: typeof import('ant-design-vue/es')['Card'];
		ACascader: typeof import('ant-design-vue/es')['Cascader'];
		ACol: typeof import('ant-design-vue/es')['Col'];
		AComment: typeof import('ant-design-vue/es')['Comment'];
		AdminIconCard: typeof import('./src/components/AdminIconCard.vue')['default'];
		AdultSearchBox: typeof import('./src/components/AdultSearchBox.vue')['default'];
		AForm: typeof import('ant-design-vue/es')['Form'];
		AFormItem: typeof import('ant-design-vue/es')['FormItem'];
		AInput: typeof import('ant-design-vue/es')['Input'];
		AInputPassword: typeof import('ant-design-vue/es')['InputPassword'];
		AInputSearch: typeof import('ant-design-vue/es')['InputSearch'];
		ALayout: typeof import('ant-design-vue/es')['Layout'];
		ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
		ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter'];
		ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
		AList: typeof import('ant-design-vue/es')['List'];
		AListItem: typeof import('ant-design-vue/es')['ListItem'];
		AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta'];
		AMenu: typeof import('ant-design-vue/es')['Menu'];
		AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
		AModal: typeof import('ant-design-vue/es')['Modal'];
		APopconfirm: typeof import('ant-design-vue/es')['Popconfirm'];
		APopover: typeof import('ant-design-vue/es')['Popover'];
		ApplyProcess: typeof import('./src/components/ApplyProcess.vue')['default'];
		ApplySearchBox: typeof import('./src/components/ApplySearchBox.vue')['default'];
		ARangePicker: typeof import('ant-design-vue/es')['RangePicker'];
		ARow: typeof import('ant-design-vue/es')['Row'];
		ASelect: typeof import('ant-design-vue/es')['Select'];
		ASelectOption: typeof import('ant-design-vue/es')['SelectOption'];
		ASpin: typeof import('ant-design-vue/es')['Spin'];
		AStatistic: typeof import('ant-design-vue/es')['Statistic'];
		AStep: typeof import('ant-design-vue/es')['Step'];
		ASteps: typeof import('ant-design-vue/es')['Steps'];
		ASubMenu: typeof import('ant-design-vue/es')['SubMenu'];
		ASwitch: typeof import('ant-design-vue/es')['Switch'];
		ATypographyText: typeof import('ant-design-vue/es')['TypographyText'];
		ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle'];
		AUpload: typeof import('ant-design-vue/es')['Upload'];
		AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger'];
		ChatText: typeof import('./src/components/ChatText.vue')['default'];
		UserIcon: typeof import('./src/components/UserIcon.vue')['default'];
		UserProfile: typeof import('./src/components/UserProfile.vue')['default'];
	}
}

export {};
